title: "Cybersecurity Labs by Pruthviraj"
description: "Hands-on cybersecurity experiments and write-ups. Learning by doing!"

theme: jekyll-theme-hacker

markdown: kramdown
highlighter: rouge

author:
  name: "Pruthviraj"
  email: "you@example.com"

show_excerpts: true
